export const userData1 = [
    {
        EventName:'Sales contract',
        PastDueDate:4,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Proforma Invoice',
        PastDueDate:3,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Letter of Credit',
        PastDueDate:36,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Order Placed',
        PastDueDate:5,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Order Confirmed',
        PastDueDate:3,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Advance payment',
        PastDueDate:28,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Booking Confirmed',
        PastDueDate:40,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Estimated Departure',
        PastDueDate:37,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Load Port Departure',
        PastDueDate:47,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Full Set of Documents Received',
        PastDueDate:43,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Discharge Port Arrival',
        PastDueDate:38,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Bill of Entry Filing',
        PastDueDate:26,
        DueToday:4,
        DueLater:15,
    },
    {
        EventName:'Customs Assessment',
        PastDueDate:20,
        DueToday:0,
        DueLater:25,
    },
    {
        EventName:'Customs Duty Paid',
        PastDueDate:12,
        DueToday:0,
        DueLater:33,
    },
    {
        EventName:'Duty Pmt Confirmed to CHA',
        PastDueDate:12,
        DueToday:0,
        DueLater:33,
    },
    {
        EventName:'Liner Invoice',
        PastDueDate:6,
        DueToday:0,
        DueLater:33,
    },
    {
        EventName:'Liner Charges Paid',
        PastDueDate:14,
        DueToday:0,
        DueLater:33,
    },
    {
        EventName:'CHA Invoice',
        PastDueDate:14,
        DueToday:0,
        DueLater:33,
    },
    {
        EventName:'CHA Charges Paid',
        PastDueDate:14,
        DueToday:0,
        DueLater:33,
    },
    {
        EventName:'BL or AWB Released',
        PastDueDate:18,
        DueToday:2,
        DueLater:33,
    },
    {
        EventName:'Delivery Order',
        PastDueDate:9,
        DueToday:0,
        DueLater:38,
    },
    {
        EventName:'Import Container Delivered',
        PastDueDate:7,
        DueToday:0,
        DueLater:0,
    },
    {
        EventName:'Destuffing/Unpacking',
        PastDueDate:8,
        DueToday:0,
        DueLater:39,
    },
    {
        EventName:'Empty Container Returned ',
        PastDueDate:15,
        DueToday:0,
        DueLater:39,
    },
    {
        EventName:'Supplier Invoice',
        PastDueDate:8,
        DueToday:0,
        DueLater:39,
    },
    {
        EventName:'Supplier Invoice Paid',
        PastDueDate:8,
        DueToday:0,
        DueLater:39,
    },
    {
        EventName:'B/E Submission to Bank',
        PastDueDate:8,
        DueToday:0,
        DueLater:39,
    },
    
]
